import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import siteMetadata from "@/data/siteMetadata";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: siteMetadata.title,
    template: `%s | ${siteMetadata.title}`,
  },
  description: "Generated by create next app",

  openGraph: {
    title: siteMetadata.title,
    description: siteMetadata.description,
    url: "./",
    siteName: siteMetadata.title,
    // images: [siteMetadata.socialBanner],
    // locale: siteMetadata.locale,
    type: "website",
  },

  twitter: {
    title: siteMetadata.title,
    card: "summary_large_image",
    // images: [siteMetadata.socialBanner],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const baseUrl = process.env.BASE_URL || "";

  return (
    <html lang={siteMetadata.language}>
      <head>
        <link
          rel="icon"
          type="image/png"
          href={`${baseUrl}/favicons/favicon-96x96.png`}
          sizes="96x96"
        />
        <link
          rel="icon"
          type="image/svg+xml"
          href={`${baseUrl}/favicons/favicon.svg`}
        />
        <link rel="shortcut icon" href={`${baseUrl}/favicons/favicon.ico`} />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href={`${baseUrl}/favicons/apple-touch-icon.png`}
        />
        <meta name="apple-mobile-web-app-title" content="JMB" />
        <link rel="manifest" href={`${baseUrl}/favicons/site.webmanifest`} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
